import toTitle from "./utils.js";
import balanceTeamsSuggestions from "./balancer.js";

const { createApp } = Vue

createApp({
  data() {
    return {
      newPlayer: {
        name: '',
        value: 5,
        selected: true
      },
      players: JSON.parse(localStorage.getItem('players')) ?? [],
      balancedTeams: []
    }
  },
  methods: {
    addPlayer () {
      const newPlayer = {
        name: toTitle(this.newPlayer.name),
        value: this.newPlayer.value,
        selected: true
      }

      const playerExists = this.players.find(p => p.name === newPlayer.name)
      
      if (playerExists) return alert("Player already exists!")
    
      this.players.push(newPlayer)
      this.newPlayer.name = ''
      document.getElementById('newPlayerNameField').focus()
    },
    removePlayer(player) {
      if(confirm('Are you sure?')) {
        this.players = this.players.filter(p => p.name !== player.name)
      }
    },
    shareTeams(suggestion) {
      const teamsText = {
        a: suggestion[0].players.map(p => p.name).join('\n'),
        b: suggestion[1].players.map(p => p.name).join('\n')
      }
      const text = `
        Team A\n${teamsText.a}\n\nTeam B\n${teamsText.b}\n\nGenerated by: ${window.location.href}`
      navigator.share({
        url: window.location.url,
        text: text
      })
    },
    viewBalancedTeams() {
      const maxSuggestions = 5
      this.balancedTeams = balanceTeamsSuggestions(this.selectedPlayers, maxSuggestions)
      Vue.nextTick(() => {
        document.getElementById("balancedTeams").scrollIntoView(true)
      })
    }
  },
  watch: {
    selectedPlayers: {
      handler() {
        localStorage.setItem('players', JSON.stringify(this.players))
      },
      deep: true
    }
  },
  computed: {
    selectedPlayers() { 
      return this.players.filter(p => p.selected)
    }
  }
}).mount('#app')