import toTitle from "./utils.js";
import balanceTeams from "./balancer.js";
import balanceTeamsSuggestions from "./balancer2.js";

const { createApp } = Vue

createApp({
  data() {
    return {
      newPlayer: {
        name: '',
        value: 5,
        selected: true
      },
      players: JSON.parse(localStorage.getItem('players')) ?? [],
      balancedTeams: []
    }
  },
  methods: {
    addPlayer () {
      const newPlayer = {
        name: toTitle(this.newPlayer.name),
        value: this.newPlayer.value,
        selected: true
      }

      const playerExists = this.players.find(p => p.name === newPlayer.name)
      
      if (playerExists) return alert("Player already exists!")
    
      this.players.push(newPlayer)
      this.newPlayer.name = ''
    },
    removePlayer(player) {
      this.players = this.players.filter(p => p.name !== player.name)
    },
    shareTeams() {
      const teamsText = {
        a: this.balancedTeams[0].map(p => p.name).join('\n'),
        b: this.balancedTeams[1].map(p => p.name).join('\n')
      }
      const text = `
        Team A\n${teamsText.a}\n\nTeam B\n${teamsText.b}\n\nGenerated by: ${window.location.href}`
      navigator.share({
        url: window.location.url,
        text: text
      })
    },
    getBalancedTeams() {
      this.balancedTeams = balanceTeamsSuggestions(this.selectedPlayers)[0]
    }
  },
  watch: {
    players: {
      handler() {
        localStorage.setItem('players', JSON.stringify(this.players))
      },
      deep: true
    }
  },
  computed: {
    selectedPlayers() { 
      return this.players.filter(p => p.selected)
    }
  }
}).mount('#app')